import type { MuscleGroup } from './muscles';

/**
 * The exercise catalogue, keyed by the muscle each movement is built around.
 * These groupings are what drive the body map, so an exercise's key here is
 * treated as its primary mover.
 */
export const exercisesByMuscle: Record<MuscleGroup, string[]> = {
  chest: [
    'High Low Cable Chest Fly', 'Reverse Wrist Push-Up', 'Barbell Floor Press', 'Standing Cable Low Chest Press',
    'Incline Barbell Bench Press', 'Superman Push-Up', 'Korean Dip', 'Low Cable Incline Bench Press',
    'Standing Cable Chest Press', 'Knuckle Push-Up', 'Cable Kneeling High To Low Fly', 'One-Arm Cable Fly',
    'Jack Push-Up', 'Punching Bag Boxing', 'Standing Downward Dog', 'Planche Dips',
    'Deep Push Up On Parallel Bars', 'Low Incline Dumbbell Fly', 'One-Arm Push-Up', 'Straight Bar Dips',
    'Scapula Push-Up', 'One-Arm Low Fly Dumbbell', 'Close Grip Dumbbell Press', 'Cable Middle Chest Fly',
    'Svend Press', 'Floor Dumbbell Press', 'Decline Push-Up', 'Smith Bench Press',
    'Dumbbell Larsen Press', 'Negative Push-Up', 'Incline Dumbbell Bench Press', 'Dumbbell Floor Chest Fly',
    'Barbell Pullover', 'Pec Deck Chest Fly', 'Hammer Grip Dumbbell Bench Press', 'Dumbbell Poliquin Press',
    'Decline Barbell Bench Press', 'Push-Up', 'Seated Cable Fly', 'Band Bench Chest Press',
    'Incline Neutral Grip Dumbbell Press', 'Kneeling Ring Push-Up', 'Band Chest Fly', 'Decline Cable Chest Press',
    'Band Warm-Up Dynamic Shoulder Stretch', 'Suspension Chest Fly', 'Spoto Press', 'Barbell Bench Press with Chains',
    'Kneeling Back Rotation Stretch', 'One-Arm Dumbbell Incline Bench Press', 'Barbell Larsen Press', 'Incline Dumbbell Chest Fly',
    'Machine Chest Press', 'Decline Chest Press', 'World\'s Greatest Stretch', 'Lying Cable Fly',
    'Resistance Band Push-Up', 'Clap Push-Up', 'Standing Incline Band Chest Fly', 'One-Arm High-to-Low Cable Fly',
    'Archer Push-Up', 'Doorway Chest Stretch', 'Dumbbell Bench Press', 'Incline Hammer Chest Press',
    'Lean Planche', 'Cross Body One-Arm Strength Press', 'Chest Dips', 'Kettlebell One Arm Floor Press',
    'Standing Press Around', 'Elbow Out Chest Stretch', 'Lying Chest Press', 'Shoulder Tap',
    'Seated Cable Chest Press', 'Ring Push-Up', 'One-Arm Dumbbell Bench Press', 'Kneeling Wide Push-Up',
    'Decline Dumbbell Bench Press', 'Wide Hand Push-Up', 'Push-Up on Parallel Bars', 'Bench Press With Resistance Band',
    'Pin Bench Press', 'One-Arm Low-to-High Cable Fly', 'Machine Chest Press Hammer Grip', 'Decline Smith Bench Press',
    'Standing Chest Opener', 'Seated Chest Clam', 'Machine Chest Fly', 'Barbell Bench Press',
    'Dumbbell Low to High Fly', 'Bent Arm Chest Stretch', 'Knee Push-Up', 'Low High Cable Chest Fly',
    'Finger Push-Up', 'Decline Dumbbell Fly', 'Smith Incline Chest Press', 'Incline Push-Up',
    'Cable Bench Press', 'Weighted Push-Up', 'Dumbbell Chest Fly', 'Poliquin Flyes',
    'Dumbbell Deep Push Up', 'Incline Bench Cable Fly'
  ],
  back: [
    'One-Arm Lat Pulldown', 'Pull-Up', 'Weighted Pull-Up', 'One-Arm Dumbbell Bent Over Scapula Row',
    'Close Grip Pull Up', 'Barbell Bent Over Row', 'One-Arm Cable Low Row', 'Seated Cable Wide Grip Row',
    'Seated Cable Row', 'Rope Straight-Arm Lat Pulldown', 'Cable Wide Grip Behind Neck Pulldown', 'Wide Grip Rear Pull-Up',
    'Chin-Up', 'Pull-Up Wide Grip', 'Suspension Row', 'Barbell Bent Over Row From Pin',
    'One-Arm Straight-Arm Cable Lat Pulldown', 'Dumbbell Kelso Shrugs', 'One-Arm Chest Supported Row Machine', 'Cable Neutral Grip Lat Pulldown',
    'One-Arm Low Cable Seated Row', 'Front Lever Pull-Up', 'Neck Side Stretch', 'Cable Lat Pulldown',
    'Bent Over Kettlebell Row', 'Machine Shrugs', 'Wide Grip Chest Supported Row', 'Gorilla Row',
    'Band Bent Over Lat Pulldown', 'Suspension Inverted Row', 'T-Bar Bent Over Row', 'Incline Bench Dumbbell Wide Row',
    'Barbell Shrug Behind The Back', 'Dumbbell Bent Over Row', 'Machine Pullover', 'T-Bar Chest Suported Row',
    'Wide Grip Lat Pulldown', 'Dumbbell Seal Row', 'Dumbbell Shoulder Shrugs', 'L Pull-Up',
    'Seated Dumbbell Shrugs', 'Standing Side Lat Stretch', 'Pull Around', 'Cable Thibaudeau Kayak Row',
    'One-Arm Landmine Bent Over Row', 'One-Arm Cable Half-Kneeling Lat Pulldown', 'One-Arm Band Kneeling Lat Pulldown', 'Australian Pull-Up Underhand Grip',
    'Lever Low Row', 'Pull-Up Neutral Grip', 'Prone Swimmer', 'Smith Shoulder Shrug',
    'Dip Shrugs', 'Chest Supported Machine Row', 'Band Pulldown Behind Neck', 'Rings Pull-Up',
    'Rowing Machine', 'Seal Row', 'Alternate Renegade Row', 'One-Arm High Row Cable',
    'Neck Curl', 'Ski Ergometer', 'Dumbbell Neutral Grip Incline Bench Row', 'Cable Close Grip Lat Pulldown',
    'Barbell Shoulder Shrug', 'Flag', 'Barbell Reverse Grip Bent Over Row', 'Lat Pulldown Machine',
    'Band High Anchor Wide Row', 'Cable Reverse Grip Pulldown', 'Incline Chest Supported Barbell Row', 'Kettlebel Renegade Row',
    'Assisted Pull-Up', 'Barbell Rear Delt Row', 'Cable Seated Row Neutral Grip', 'One-Arm Cable Row',
    'Lever High Row', 'Trap Bar Shrugs', 'Inverted Row (Australian)', 'Pendlay Row',
    'Seated Cable Low Row Neutral Grip', 'Lever Back Extension', 'Dumbbell Pullover with Legs Raised', 'Cable Seated Supine Grip Row',
    'Straight-Arm Lat Pulldown', 'Kneeling Cable Lat Pulldown', 'Narrow Grip Australian Pull-Up With Rings', 'Close Grip Landmine Row',
    'Back Lever', 'One-Arm Seated Row', 'Cable Shrug', 'Barbell Incline Wide Grip Row',
    'Band Assisted Pull Up', 'Inverted Shrug', 'Dumbbell Lat Pullover', 'Dumbbell Incline Chest Supported Lateral Raises',
    'Front Lever', 'One-Arm Lever High Row', 'Negative Pull-Up', 'Smith Bent Over Row',
    'Double Dumbbell Bent Over Row'
  ],
  shoulders: [
    'Barbell Behind Neck Shoulder Press', 'Dumbbell Push Press', 'Band Shoulder Press', 'Plate Front Raise Drive',
    'Arm Circles', 'Dumbbell Front Raise', 'Cable Front Raise', 'One-Arm Cable Lateral Raise',
    'Dumbbell Seated Lateral Raise', 'Barbell Push Press', 'Straddle Planche', 'Seated Cuban Press',
    'One-Arm Shoulder Press Dumbbell', 'One-Arm Cable Front Raise', 'Bent Over Dumbbell Lateral Raise', 'Barbell Overhead Press',
    'Lever Seated Hammer Grip Shoulder Press', 'Pike Push-Up Between Benches', 'Cable Upright Row', 'Lateral to Front Raise',
    'Dumbbell Incline T Raise', 'Cable Supinated Face Pull', 'Dumbbell Cuban Rotation', 'Seated Face Pull',
    'Kettlebell Around the Head Rotation', 'Standing Dumbbell Shoulder Press', 'Lying Cable Face Pull', 'Full Planche',
    'Medicine Ball Slam', 'Pike Push-Up Between Chairs', 'Cable Face Pull', 'Barbell Wide Grip Upright Row',
    'Seated Dumbbell Shoulder Press', 'Machine Reverse Flyes', 'One-Arm Landmine Standing Shoulder Press', 'Dumbbell Half Kneeling Shoulder Press',
    'Half Kneeling Shoulder Dumbbell Press', 'Barbell Narrow Grip Upright Row', 'Machine Shoulder Press', 'Band Pass Through Shoulders',
    'Weighted Woodchopper', 'Dumbbell Upright Row', 'Lying Cross Lateral Cable Fly', 'Static Front Hold',
    'Kettlebell Clean and Jerk', 'Dumbbell Alternate Hammer Front Raise', 'Seated Shoulder External Rotation', 'Plate Bus Driver',
    'Pike Push-Up', 'Ring Face Pull', 'Smith Seated Behind Neck Press', 'Incline Powell Raise',
    'Standing Cuban Press', 'Barbell Shoulder Grip Upright Row', 'One-Arm Rear Delt Fly', 'Cable Rear Delt Fly (Reverse Fly)',
    'Arm Circle', 'Dumbbell Seated Bent Over High Row', 'One-Arm Cable Bent Over Lateral Raise', 'Barbell Front Raise',
    'Seated Arnold Dumbbell Press', 'Band Lateral Raise', 'Dumbbell Standing Alternate Press', 'Landmine Lateral Raise',
    'Banded Face Pull', 'Handstand Push-Up', 'Alternate Bent Over Dumbbell Reverse Fly', 'One-Arm Dumbbell Supported Bent Over Lateral Raise',
    'Cable Incline Y Raise Back Supported', 'Plate Front Raise', 'Seated Bent Over Dumbbell Lateral Raise', 'One-Arm Dumbbell Incline Lateral Raise',
    'Cable Lateral Raise', 'Trap Y Raise', 'Band Upright Row', 'Dumbbell Lateral Raise',
    'Dumbbell Lu Raises', 'Dumbbell Poliquin Lateral Raise', 'Cable Seated Rear Lateral Raise', 'Cable Leaning Lateral Raise',
    'Dumbbell Snatch', 'Smith Machine Upright Row', 'One-Arm Dumbbell Lateral Raise', 'Chest Supported Lateral T Raise',
    'Dumbbell Standing Driver', 'One-Arm Kettlebell Overhead Press', 'Turkish Get Up', 'One-Arm Landmine Half Kneeling Shoulder Press',
    'Seated Shoulder Press Neutral Grip', 'Landmine Press', 'Dumbbell Alternate Front Raise', 'Powell Raise',
    'One-Arm Cable Rear Delt Fly', 'Pike Push-Up On Bench', 'Rear Deltoid Stretch', 'Machine Lateral Raise',
    'Dumbbell Rear Delt Row', 'Dumbbell Incline Rear Lateral T Raise', 'Smith Shoulder Press', 'Kettlebell Windmill',
    'Cable Y Raise', 'Tsunami Overhead Press', 'Barbell Rear Delt Raise', 'Bird Dog Plank',
    'Seated Barbell Shoulder Press', 'Wall Angel', 'Handstand Hold'
  ],
  legs: [
    'Sliding Leg Curl', 'Rocking Half Frog Stretch', 'Standing Tibialis Raise', 'Anderson Squat',
    'Pistol Squat', 'Weighted Sissy Squat', 'Narrow Stance 45 Degree Leg Press', 'Barbell Calf Raise',
    'Seated Single Leg Hamstring Stretch', 'Half Squat', 'Deficit Deadlift', 'Weighted Seated Calf Raise',
    'Smith Chair Squat', 'Seated Hip Adduction', 'Barbell Squat', 'Pin Squat',
    'Standing Forward Bend', 'Calf Leg Press', 'Snatch', 'Stationary Bike',
    'Lying Butterfly Pose', 'Deadlift', 'Barbell Step-up', 'Single-Leg Calf Raise with Dumbbell',
    'Lowbar Squat', 'Machine Belt Squat', 'Knee To Chest Stretch', 'Power Clean',
    'High-Bar Squat', 'Box step-up', 'Lying Quadriceps Stretch', 'Deep Squat to Wide Fold with Foot Hold',
    'Stair Climber', 'Standing Quadriceps Stretch', 'Leg Swings', 'Dumbbell Split Squat',
    'Barbell Sumo Squat', 'Split Squat Front Foot Elevated', 'Bulgarian Bag Walking Lunges', 'Leg Press Wide Stance',
    'Roll Foot', 'Seated Leg Curl', 'Nordic Hamstring Curl', 'Smith Machine Glute Kickback',
    'Resistance Band Hip Adduction', 'Seated Calf Raise', 'Dumbbell Squat', 'Standing Leg Curl',
    'Terminal Knee Extension', 'Bulgarian Squat Smith', 'Single Leg Press', 'Jump Rope',
    'Treadmill Climbing', 'Front Squat', 'Lunge Stretch', 'Smith Squat',
    '90 To 90 Stretch', 'Downward Dog', 'Poliquin Step-Up', 'Hopping High Knee Tap',
    'One-Arm Kettlebell Swing', 'Single-Leg Deadlift', 'Single-Leg Calf Raise', 'Half Kneeling Quad Stretch',
    'Rotary Calf Raise', 'Barbell Walking Lunges', 'Dumbbell Jump', 'Box Jumps',
    'Smith Hack Squat', 'Single Leg Seated Calf Machine Raise', 'Hang Power Clean', 'Walking Lunges',
    'Barbell Hack Squat', 'Smith Split Squat', 'Snatch Pull', 'Squat',
    'Dumbbell Cossack Squat', 'Band Lying Leg Curl', 'Dumbbell Walking Lunges', 'Barbell Rack Pull',
    'Barbell Straight Leg Deadlift', 'Barbell Thruster', 'Standing Calf Raise', 'Prowler Sled',
    'Kickboxing', 'Smith Calf Raises', 'Trap Bar Deadlift', 'Wall Sit',
    'Goblet Squat', 'Side Lunges', 'Barbell Split Squat', 'Split Squat',
    'Kettlebell Rear Lunge', 'Dumbbell Goblet Squat', 'Dumbbell Straight Leg Deadlift', 'Weighted Cossack Squat',
    'Dumbbell Side Lunges', 'Crossack Squat', 'Hip Circles', 'Barbell Reverse Lunges',
    'Machine Hack Squat', 'Sumo Squat', 'Glute-Ham Raise 1/2', 'Seated Leg Extension Machine',
    'Plyo side lunge', 'Kettlebell Clean', 'Seated Single Leg Curl', 'Forward Band Monster Walk',
    'Smith Squat To Bench', 'Cable Hip Adduction', 'Kettlebell Deadlift', 'Dumbbell Standing Calf Raises',
    'Landmine Squat', 'Single-Leg Cable Leg Curl', 'Kettlebell Swing', 'Elliptical Trainer',
    'Smith Seated Calf Raise', 'Machine Reverse Hack Squat', 'Assisted Pistol Squat', 'Pin Front Squat',
    'Dumbbell Step-Up', 'Smith Kneeling Hip Thrust', 'Rear Lunge', 'Broad Jump',
    'Clean Squat', 'Side Lying Quadriceps Stretch', 'Lizard Pose', 'Bulgarian Jump Squat',
    'Rocking Frog', 'Smith Front Squat', 'Zercher Squat', 'Burpee',
    'Smith Zercher Squat', 'Superman', 'Butterfly Stretch', 'Prone Lying Leg Curl',
    'Pogo Jumps', 'Jumping Jacks', 'Barbell Cossack Squat', 'Pistol Box Squat',
    'Machine Calf Raises', 'Smith Rear Lunge', 'Stability Ball Wall Squat', 'Vertical Leg Press Smith Machine',
    'Single-Leg Lying Curl', 'Sumo Squat With Smith', 'Lever Horizontal Leg Press', 'Walking Cardio',
    'Single-Leg Box Jump', 'Dumbbell Bulgarian Squat', 'Single Leg Dumbbell Deadlift', 'Weighted Pistol Squat',
    'Swiss Ball Leg Curl', 'Box Squat', 'Clean and Jerk', 'Jump Squat',
    'Assault Air Bike', 'Single-Leg Seated Calf Raise with Dumbbell', 'Sissy Squat', 'Reverse Nordic Curl',
    'Kneeling Hamstring Stretch', 'Bench Front Squat', 'Dumbbell Deadlift Straight Legs', 'Cable Romanian Deadlift',
    'Seated Forward Fold', 'Jefferson Curl', 'Side Leg Swings', 'Leg Press',
    'Cyclist Squat', 'B Stance Romanian Deadlift', 'Dumbbell Lying Leg Curl', 'Treadmill Run',
    'Dumbbell Romanian Deadlift', 'Sumo Squat off Stepbox', 'Dumbbell Lunges', 'Smith Romanian Deadlift',
    'Lunges', 'Cable Step Up', 'Roll Calves', 'Dumbbell Deadlift',
    'Single-Leg Extension', 'Happy Baby Pose', 'Ring Leg Curl', 'Cable Terminal Knee Extension',
    'Single Leg Smith Calf Raise', 'Butterfly Lean Forward Stretch', 'Running', 'Barbell Overhead Squat',
    'Band Squat', 'Barbell Bulgarian Squat'
  ],
  glutes: [
    'Dumbbell Single Leg Hip Thrust', 'Kneeling Resistance Band Glute Kickback', 'Dumbbell Reverse Lunge off Step', 'Cable Hip Abducction',
    'Barbell Good Morning', 'Mini Band Glute Bridge', 'Smith Machine Good Morning', 'Seated Band Hip Abduction',
    'Donkey Kick', 'Hip Thrust Smith Machine', 'Single Leg Romanian Deadlift', 'Weighted Back Extension',
    'Seated Figure 4 Stretch', 'Band Standing Balance Glute Kickback', 'Barbell Rear Lunge On Step', 'Figure 4 Stretch on Chair',
    'Hip Thrust', 'Side Plank Hip Abduction', 'Glute Bridge', 'Glute Cable Kickback',
    'Weighted Glute Bridge', 'Side Lying Hip Abduction', 'Barbell Glute Bridge', 'Sumo Deadlift',
    'Pigeon Pose', 'Glutes Roll', 'Standing Hip Abduction', 'Back Extension',
    'Dumbbell Rear Lunge', 'Cable Pull Through', 'Glute Machine Kickback', 'Lying Knee To Chest Stretch',
    'KAS Glute Bridge', 'Dumbbell Sumo Squat', 'Glute Bridge on Bench', 'Single Leg Weighted Glute Bridge',
    'Hip Hinge', 'Back Extension With Dumbbell', 'Romanian Deadlift', 'Kettlebell Goblet Squat',
    'Seated Hip Abduction', 'Band Hip Abduction', 'Band Reverse Hyperextension', 'Lateral Monster Walk',
    'Frog Pump', 'Bulgarian Squat', 'Machine Hip Thrust', 'Side Plank Clamshell',
    'Child\'s Pose', 'Deadlift from Blocks', 'Band Lying Clamshells', 'Seated Good Morning',
    'Bird Dog', 'Dumbbell Hip Thrust', 'Glute Bridge Single Leg'
  ],
  biceps: [
    'Band Biceps Curl', 'Zottman Curl', 'Close-grip EZ Bar Curl', 'Bayesian Cable Curl',
    'Bar Cable Biceps Curl', 'Dumbbell Spider Curl', 'Seated Dumbbell Curl', 'Spider Hammer Curl',
    'Ring Muscle Up', 'Single Dumbbell Curl', 'Dumbbell Supinated Preacher Curl', 'One-Arm Machine Preacher Curl',
    'EZ-Bar Preacher Curl', 'Double Dumbbell Preacher Curl', 'Dumbbell Incline Hammer Curl', 'Cable Squatting Curl',
    'One-Arm Cable Biceps Curl', 'TRX Biceps Curl', 'EZ-Bar Biceps Curl', 'Band Hammer Curl',
    'Barbell Prone Incline Curl', 'Arm Blaster Biceps Dumbbell Curl', 'Dumbbell Hammer Curl', 'Biceps Barbell Curl',
    'Dumbbell Alternate Supinated Curl', 'Bayesian Cable Curl Seated', 'Seated Hammer Curl', 'One-Arm Preacher Hammer Curl',
    'Weighted Chin Up', 'Wide Grip Standing Barbell Curl', 'Dumbbell Drag Curl', 'Dumbbell Biceps Curl',
    'Dumbbell Incline Alternate Supinated Curl', 'Machine Biceps Curl', 'Hercules Curl', 'Barbell Preacher Curl',
    'EZ-Bar Spider Curl', 'Incline Cable Curl', 'Bayesian Cable Curl (Face Away)', 'Dumbbell Cross Body Hammer Curl',
    'Close Grip Biceps Curl', 'One-Arm Hammer Cable Curl', 'Barbell Drag Curl', 'Concentration Hammer Curl',
    'Kettlebell Biceps Curl', 'Preacher Hammer Curl', 'Dumbbell Concentration Curl', 'Alternate Dumbbell Hammer Curl',
    'Seated Incline Biceps Curl', 'One-Arm Dumbbell Preacher Curl', 'Dumbbell Seated Alternate Hammer Curl', 'Barbell Wall Curl',
    'Rope Cable Hammer Curl', 'Machine Preacher Curl', 'Cable Preacher Curl', 'Alternate Biceps Curl'
  ],
  triceps: [
    'Diamond Push-Up', 'Weighted Dips', 'Cable Incline Skull Crusher', 'Cable Cross Triceps Extension',
    'Triceps Cable Pushdown Reverse Grip', 'JM Press', 'Cross Arms Push-Up', 'Standing One Dumbbell French Press',
    'Knee Close Grip Push-Up', 'Lying EZ-Bar Triceps Extension', 'Close Grip Smith Bench Press', 'Incline Close Grip Push-Up',
    'EZ-Bar Seated Triceps Extension', 'Cobra Push-Up', 'Tate Press', 'Overhead Triceps Stretch',
    'Weighted Bench Dips', 'Close Grip Incline Dumbbell Bench Press', 'One-Arm Katana Triceps Overhead Extension', 'Lying Barbell Triceps Extension (Skullcrusher)',
    'Ring Triceps Extension', 'Planche Push-Up', 'One-Arm Cable Cross Body Triceps Extension', 'Bird Dog Push-Up',
    'Close Grip Push-Up', 'Frog Planche', 'Dips', 'Triceps Push-Up',
    'One-Arm Reverse Grip Triceps Cable Pushdown', 'One-Arm Triceps Cable Pushdown', 'High Pulley Overhead Triceps Extension', 'Cable Overhead Triceps Extension',
    'One-Arm Dumbbell Seated Kickback', 'EZ-Bar Tricep Pushdown', 'Seated Triceps Bench Dip', 'Ring Dips',
    'Dumbbell Lying Triceps Extension', 'Suspension Triceps Extension', 'Dumbbell Seated Triceps Extension', 'Machine Triceps Extension',
    'Triceps Pushdown V-Bar', 'Assisted Machine Dips', 'One-Arm Cable Triceps Pushdown', 'Overhead Cable Triceps Extension (bar)',
    'Cable Triceps Pushdown', 'Standing Overhead Barbell Triceps Extension', 'Underhand Triceps Extension', 'Katana Triceps Extension',
    'Decline Barbell French Press', 'Triceps Cable Kickback', 'Weighted Muscle-Up', 'Muscle-up',
    'California Press', 'Overhead Band Triceps Extension', 'Incline Barbell Triceps Extension', 'Decline Diamond Push-Up',
    'Seated Cable Horizontal French Press', 'Full Planche Push-Up', 'Incline Dumbbell Triceps Extension', 'Cable Double-Arm Tricep Kickback',
    'Knee Diamond Push-Up', 'Band Triceps Pushdown', 'Seated Dip Machine', 'One-Arm Cable Pushdown',
    'One-Arm Overhead Triceps Extension', 'Reverse Hand Push-Up', 'Rope Triceps Pushdown'
  ],
  forearms: [
    'Dumbbell Lying Pronation', 'One-Arm Neutral Wrist Dumbbell Curl', 'One-Arm Wrist Curl Dumbbell', 'EZ-Bar Seated Reverse Wrist Curl',
    'One-Arm Dumbbell Supination', 'Farmer Walk', 'Barbell Standing Wrist Curl', 'Dumbbell Standing Wrist Curl',
    'Wrist Push-Up', 'Barbell Standing Back Wrist Curl', 'Wrist Roller', 'EZ-Bar Seated Wrist Curl',
    'Barbell Reverse Grip Forearm Curl', 'Unilateral Farmer Walk', 'EZ-Bar Reverse Spider Curl', 'Dumbbell Farmer Carry',
    'EZ-Bar Reverse Grip Biceps Curl', 'Dumbbell Standing Reverse Wrist Curls', 'Dead Hang', 'Barbell Reverse Wrist Curl',
    'Reverse Grip Cable Curl', 'Dumbbell Biceps Reverse Curl', 'Cable Wrist Curl', 'Seated Cable Wrist Curl',
    'Hanging Scapular Retractions', 'Barbell Wrist Curl', 'Hand Gripper', 'One-Arm Dumbbell Reverse Wrist Curl',
    'Cable Standing Wrist Roll'
  ],
  abs: [
    'Knee Tuck Crunch', 'Bodyweight Windmill', 'Rotary Torso', 'L-Sit',
    'Band Standing Side Bend', 'Sitting Twist', 'Cable Twist (horizontal)', 'Leg In and Out',
    'Weighted Decline Crunch', 'Hanging Scissors Kicks', 'Ab Wheel Rollout', 'Dumbbell Side Bridge',
    'Abdominal Crunches', 'Band Standing Twisting Crunches', 'Hollow Body Hold', 'Weighted Straight Arm Crunch',
    'Straight Leg Raise on Dip Bars', 'Cable Twist (up down)', 'Seated Alternate Crunches', 'Hanging Knee To Chest',
    'Incline Bench Leg Raises', 'Dragon Flag', 'Weighted Sit Up', 'Dead Bug',
    'Med Ball Russian twist', 'Band Pallof Press', 'Band Russian Twist', 'Band Standing Crunches',
    'Cable Kneeling Side Crunch', 'Machine Abdominal Crunches', 'Bicycle Crunches', 'Scissors',
    'Low Cable Horizontal Pallof Press', 'Hanging Knees to Elbows', 'Weighted Dead Bug', 'Stability Ball Crunch',
    'Kneeling Band Abs Crunches', 'Barbell Standing Twist', 'Sit Up', 'Lying Stright Leg Raise',
    'Machine Lying Crunch', 'Ring Pike', 'Dead Bug with Ball', 'Plank',
    'Hanging Knees to Elbows Waist', 'Seated Reverse Circle Crunches', 'V-Up', 'Band Twist (horizontal)',
    'V-Sit Crunch', 'Toes To Bar', 'Standing Air Bike', 'Weighted Plank',
    'Air Bike', 'Mountain climber', 'Capitan\'s Chair Straight Leg Raises', 'Incline Twisting Sit Up',
    'Shoulderstand Pose', 'Hanging Knee Circles', 'Frog Crunch', 'Hanging Leg Raise To Bar',
    'Hanging Straight Leg Raise', 'High To Low Band Woodchopper', 'Crab Pose', 'Band Half Kneeling Chop',
    'Weighted Hollow Body Hold', 'Knee Raise Ab Coaster', 'Seated Machine Trunk Rotation', 'Seated Leg Raise',
    'Side Crunch', 'Suspension V-Ups', 'Reverse Crunches', 'Dumbbell Standing Side Bend',
    'Toe Touches', 'Dumbbell Russian Twist', 'Hanging Half Windmill', 'Upward Dog',
    'Weighted Russian Twist', 'Seated Flutter Kick', 'Side Plank', 'Swiss Ball Plank',
    'Saw Plank', 'Standing Cable Ab Crunch', 'Barbell Rollout - Kneeling', 'Bottom up rotation',
    'Band Kneeling Twisting Crunch', 'Bear Plank', 'Lying Spinal Twist', 'Janda Sit Up',
    'Standing Russian Twist', 'TRX Single Leg Bird Dog', 'Abdominal Vaccum', 'Seated Ab Cable Crunch',
    'Weighted Hanging Leg Raise', 'Weighted Ab Crunches', 'Opposite side elbow to knee', 'Cable Horizontal Pallof Press',
    'Landmine Twist', 'Band Bicycle Crunches', 'Hanging Oblique Knee Raise', 'Ankle Taps',
    'Cat Cow', 'Hanging Knee Raises', 'Kneeling Cable Abs Crunches', 'Decline Crunch',
    'Seated Barbell Twist', 'Captains Chair Knee Raises'
  ],
};

/** Flat, de-duplicated list of every exercise we know about. */
export const exerciseLibrary: string[] = Array.from(
  new Set(Object.values(exercisesByMuscle).flat())
);
